{{- include "agones-palworld.validate" . }}
{{- if .Values.secret.enabled }}
{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agones-palworld.fullname" . }}-admin
  labels:
    {{- include "agones-palworld.labels" . | nindent 4 }}
type: Opaque
stringData:
  palworld_admin_password: |-
    {{- $name := printf "%s-admin" (include "agones-palworld.fullname" .) }}
    {{- $existing := (lookup "v1" "Secret" .Release.Namespace $name) }}
    {{- if and $existing $existing.data.palworld_admin_password }}
    {{ index $existing.data "palworld_admin_password" | b64dec }}
    {{- else if .Values.secret.autoGenerate }}
    {{ randAlphaNum (int .Values.secret.length) }}
    {{- else }}
    {{- fail "secret.existingSecret is empty and secret.autoGenerate is false; no password source." }}
    {{- end }}
{{- end }}
{{- end }}
